### ISSUE TITLE
/f help command throwing error

### ISSUE THREAD

**Issue by cdog580** [Aquerr/EagleFactions#21]
## Environment

* **Sponge Version:** 
Minecraft: 1.12.2
    SpongeAPI: 7.0.0-SNAPSHOT-963ff064
    SpongeVanilla: 1.12.2-7.0.0-BETA-374

* **Plugin Version:** 
0.9.6

## What happens?

throwing error:
Error occurred while executing command: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
[13:52:30 ERROR] [Sponge]: Error occurred while executing command 'f help' for source DedicatedServer: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
        at io.github.aquerr.eaglefactions.commands.HelpCommand.execute(HelpCommand.java:71) ~[HelpCommand.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:181) ~[ChildCommandElementExecutor.class:1.12.2-7.0.0-BETA-374]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-7.0.0-BETA-374]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-374]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-374]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:382) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:350) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

## Expected result

factions help displayed

**Comment by Aquerr** [comment]
There is currently no version of Eagle Factions for 1.12.2.

That’s why it is crashing.

There is nothing I can do with this. 
You need to wait until the plugin will be available for 1.12.2 and download **correct** version.
