### ISSUE TITLE
Error in console when someone speak (1.11.2)

### ISSUE THREAD

**Issue by yodaa59** [Aquerr/EagleFactions#23]
Hello,

I have thios error when someone speak !

[Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=eaglefactions, name=Eagle Factions, version=0.9.7, description=A factions plugin that will make managing your battle-server easier. :), authors=[Aquerr], source=/home/minecraft/faction01/mods/EagleFactions-1.11.2-v0.9.7.jar}
java.lang.NullPointerException
        at io.github.aquerr.eaglefactions.listeners.ChatMessageListener.onChatMessage(ChatMessageListener.java:115) ~[ChatMessageListener.class:?]
        at org.spongepowered.common.event.listener.ChatListener_ChatMessageListener_onChatMessage80.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2476-6.1.0-BETA-2715]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11.2-2476-6.1.0-BETA-2715]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:265) ~[SpongeModEventManager.class:1.11.2-2476-6.1.0-BETA-2715]
        at net.minecraftforge.fml.common.eventhandler.EventBus.postForgeAndCreateSpongeEvent(EventBus.java:595) ~[EventBus.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$zph000(NetHandlerPlayServer.java:2571) ~[mi.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:888) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-2476-6.1.0-BETA-2715]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-2476-6.1.0-BETA-2715]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-2476-6.1.0-BETA-2715]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjm000(SourceFile:539) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:257) [SpongeImplHooks.class:1.11.2-2476-6.1.0-BETA-2715]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhl000(MinecraftServer.java:3969) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Aquerr** [comment]
Which spongeforge are you using and which version of Eagle Factions?

Does it happens when someone is in a faction? or not?

**Comment by yodaa59** [comment]
spongeforge-1.11.2-2476-6.1.0-BETA-2715.jar
EagleFactions-1.11.2-v0.9.7.jar

and when the person is not in faction

**Comment by Aquerr** [comment]
Strange.... I have tested it myself now and It works fine.

Are you using any other plugins that changes how chat looks? If you do, please tell me their names.

**Comment by yodaa59** [comment]
I use bungeechat on  my network.

I know nucleus can change look for chat but i think i disabled it, and after, luckperms for prefix

**Comment by abused** [comment]
Hi, this started occurring to me as well as soon as i updated to 0.9.7 today, nothing editing chat as far as the plugins i see here

**Comment by Aquerr** [comment]
Hmmm... I need to take a look at this then. I am very sorry that something like that is happening.

I will test it with luckperms and bungeechat as soon I will have some free time. 
You can use 0.9.6 for now if it is very annoying.

It would be very good if someone of you could send me some „example server files” where it happenes.

Have also one more question, does chat work properly in the game? Or is the error showing in the chat too?

**Comment by abused** [comment]
Chat works perfectly fine in game, nothing seems wrong its just the error in console
these are my plugins/mods 
https://gyazo.com/83edd94a89eee2550f85cb4e4543a5d5
https://gyazo.com/ca140fb64c0966bba21c8dcca446e72e
Again i'm on 1.10.2 the author of this issue is on 1.11.2

**Comment by yodaa59** [comment]
Hello,

For information, it's appear when someone speak when he is in faction. And in the chat, the plugin dont write the faction name ! the message comming but without faction prefix :)

**Comment by Aquerr** [comment]
This will help a lot. I will probably take a look at this today or tomorrow.

**Comment by Aquerr** [comment]
@abused I have tested my plugin with most of your mods/plugins and It works fine.
@yodaa59 @abused Could you provide me a config file which you are using for Eagle Factions? (entire content of the file "Settings.conf")
I think that we can find a reason of this issue there.

**Comment by abused** [comment]
Yeah sure
https://www.dropbox.com/s/kd1a7fcxzfoa4c0/Settings.conf?dl=0

**Comment by Aquerr** [comment]
As I can see, you are missing few new things that has been added to the config file. That's why the error is showing in the console.

Delete your settings.conf file and let the server generate it again. :) this should help.

**Comment by yodaa59** [comment]
Hello,
I check the config file and have no error now :) it write the faction name but he don't write the rank on server :(

Can you help me with this ? i use bungeechat and luckperms and when saying it write: "[faction][rank in fac] <pseudo> message" but i want the meta prefix from luckperms :)

thanks a lot

**Comment by Aquerr** [comment]
I have found a mistake in my code and it is fixed now. 

I will release a fix on sunday together with the fix for another issue. I don’t think I will have time to do this earlier. ;)

**Comment by Aquerr** [comment]
This should be fixed in the 0.9.8 release.

I am closing this issue.
