### ISSUE TITLE
Error on user login: Could not pass ClientConnectionEvent$Join$Impl to Plugin eaglefactions

### ISSUE THREAD

**Issue by Thanatosus** [Aquerr/EagleFactions#74]
## Environment

* **Sponge Version:** spongeforge-1.12.2-2705-7.1.0-beta-3126

* **Plugin Version:** eaglefactions-1.12.2-v0.9.15.jar

* **Forge Version:** forge-1.12.2-14.23.4.2705-universal.jar

## What happens?

Hello,

Every time when a user log-in to the server I had a error message in the server-terminal (see the error stack below please).

Thank you for your work on EagleF
Have a nice day,
Thanatosus

## Expected result

No more error (?)

## More information
[18:03:01] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=eaglefactions, name=Eagle Factions, version=0.9.15, description=A factions plugin that will make managing your battle-server easier. :), authors=[Aquerr], source=/var/minecraft/minecraft_forge_2705_1.12/./mods/plugins/eaglefactions-1.12.2-v0.9.15.jar}
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218) ~[minecraft_server.1.12.2.jar:?]
        at io.github.aquerr.eaglefactions.logic.MainLogic.addWorld(MainLogic.java:309) ~[MainLogic.class:?]
        at io.github.aquerr.eaglefactions.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:43) ~[PlayerJoinListener.class:?]
        at org.spongepowered.common.event.listener.JoinListener_PlayerJoinListener_onPlayerJoin89.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3126]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3126]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1672) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Thanatosus** [comment]
Hello,

Sure. https://pastebin.com/Wuk8xFuY

**Comment by Aquerr** [comment]
@Thanatosus Okey, I found the problem. Dumb of me that I made such a mistake in the code. I will release a fix asap. 😄

**Comment by Aquerr** [comment]
@Thanatosus Should be fixed now in the 0.9.16 😄 

Check if it is working now and close the issue if it is. :)

**Comment by Thanatosus** [comment]
@Aquerr Thank you very much. It's perfect, no more errors so :)
It's very nice to see a dev who really cares about his plug-in ^^
